wireless/bluetooth/bt_hcicore.c: Fix an unused warning
This fixes the following warning:

bluetooth/bt_hcicore.c:143:12: error: unused function 'bt_send' [-Werror,-Wunused-function]
static int bt_send(FAR const struct bt_driver_s *btdev,
           ^