Merged in alinjerpelea/nuttx (pull request #924)
drivers: usbdev: usbmsc: fix usbmsc_exportluns declaration

* drivers: usbdev: usbmsc: fix usbmsc_exportluns declaration

    fixes the following error
    apps/system/usbmsc/usbmsc_main.c:567:
    undefined reference to `usbmsc_exportluns'

    Signed-off-by: Alin Jerpelea <alin.jerpelea@sony.com>

* configs: spresense: nsh: register the procfs

    this is a configuration change in sync with the other ones

    Signed-off-by: Alin Jerpelea <alin.jerpelea@sony.com>

* configs: spresense: enable READLINE_CMD_HISTORY

    we are following the default spresense board configuration
    regarding CMD HISTORY configuration

    Signed-off-by: Alin Jerpelea <alin.jerpelea@sony.com>

* configs: spresense: enable by default SPI 4 and 5

    we are following the default spresense board configuration
    regarding SPI configuration

    Signed-off-by: Alin Jerpelea <alin.jerpelea@sony.com>

* configs: spresense: add I2C configuration

    in sync with the default spresense board configuration

    Signed-off-by: Alin Jerpelea <alin.jerpelea@sony.com>

Approved-by: Gregory Nutt <gnutt@nuttx.org>