libc/mcount: add armv6m mcount implementation
armv6m does not support the complete Thumb-2 instruction set, resulting in compilation errors

CC:  dirent/lib_alphasort.c mcount.S: Assembler messages:
mcount.S:33: Error: cannot honor width suffix -- `bic r1,lr,#1'
mcount.S:35: Error: cannot honor width suffix -- `bic r0,r0,#1'
mcount.S:37: Error: cannot honor width suffix -- `pop {r0,r1,r2,r3,ip,lr}'

Signed-off-by: yinshengkai <yinshengkai@xiaomi.com>