arch/Toolchain.defs: revise LDELFFLAGS
This adjusts LDELFFLAGS so that `-r` is not used with `-e _start`
together.

This solves the build issues with `maix-bit/elf`:

```
LD: errno.o
riscv64-unknown-elf-ld: warning: cannot find entry symbol __start;\
  defaulting to 0000000000000000
```

or later

```
LD: nuttx
riscv64-unknown-elf-ld: \
/tmp/nuttx/staging/libapps.a(symtab.c.tmp.apps.examples.elf_1.o):\
(.rodata.g_elf_exports+0x38): undefined reference to `_start'
```

Signed-off-by: Yanfeng Liu <p-liuyanfeng9@xiaomi.com>