compiler/diagnostic: Replace all #warning to #pragma message
Since some compilers(MSVC) do not support the syntax of "#warning", use "#pragma message" to enhance portability

D:\archer\code\nuttx\net\can\can_sockif.c(680,1): fatal  error C1021: invalid preprocessor command

Reference:
https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1021?view=msvc-170

Signed-off-by: chao an <anchao@xiaomi.com>