sim/userfs: add worker thread config to fix build break
net/loopback.c:75:4: error: #error Worker thread support is required (CONFIG_SCHED_WORKQUEUE)
 #  error Worker thread support is required (CONFIG_SCHED_WORKQUEUE)
    ^~~~~
make[1]: *** [loopback.o] Error 1

Change-Id: I549692fa271a65b1f70a80b8988e84ae0be886f4
Signed-off-by: liuhaitao <liuhaitao@xiaomi.com>