libc/stdio: in dtoa(), up_interrupt_context() is used in a debug assertion.  up_interrupt_context() is not available in the user-mode phase of the PROTECTED or KERNEL build configurations.  In those configurations, enabling libc floating point support and debug assertions will result in an undefined reference to up_interrupt_context().