spinlock: fix struct comparison for ticket spinlock
Previously compilation with ticket spinlock enabled failed for the
rp2040 board due to comparisons between structs:

```
CC:  netdb/lib_proto.c chip/rp2040_testset.c: In function 'up_testset':
chip/rp2040_testset.c:73:11: error: invalid operands to binary == (have 'spinlock_t' {aka 'union spinlock_u'} and 'union spinlock_u')
   73 |   if (ret == SP_UNLOCKED)
      |           ^~
```

Now all occurrences of comparisons are replaced with the existing macro
`spin_is_locked`.
Most of these occurrences were not relevant, since they were located in
the spinlock code branches for "non-ticket" mode (with `spinlock_t`
being an integer).
But in order to keep everything clear and predictable, we want to avoid
potential struct comparisons everywhere.