serial: fix build break caused by previous patch
serial/serial_dma.c: In function 'uart_check_signo':
serial/serial_dma.c:82:18: error: 'SIGINT' undeclared (first use in this function)
   82 |           return SIGINT;
      |                  ^~~~~~

This is canused by:
remove #include <nuttx/mqueue.h> from include/nuttx/fs/fs.h in:
d1ede9ac904d331ee6b22343f5d7f0ead7a113a6

Change-Id: I20260ad3bcceb30207c9c12041dd95de41e13777