tlsr82: disable CONFIG_RW_SPINLOCK
tlsr82 does not support atomic

include/nuttx/spinlock.h:45:25: fatal error: stdatomic.h: No such file or directory

Signed-off-by: chao an <anchao@xiaomi.com>