prevent GMAC txtimeout from always firing
     - and fix txbuffer leak during high-volume sends
     - improves reliability but may not have solved all issues

Squashed commit of the following:

commit 675b80cb97602fea74a119b1ce0b71e9a60f6314
Author: Adam Feuer <adam@adamfeuer.com>
Date:   Tue Feb 25 13:06:08 2020 -0800

    Update arch/arm/src/sama5/sam_gmac.c

    Co-Authored-By: Abdelatif Guettouche <abdelatif.guettouche@gmail.com>

commit 8384e5ca37339e6597a2967552807095646809cf
Author: Adam Feuer <adam@starcat.io>
Date:   Tue Feb 25 11:35:34 2020 -0800

    prevent GMAC txtimeout from always firing

     - and fix txbuffer leak during high-volume sends
     - improves reliability but may not have solved all issues

    Squashed commit of the following:

    commit 3c20427693c71e3882ce94762bf89f40001440e6
    Author: Adam Feuer <adam@starcat.io>
    Date:   Tue Feb 25 11:33:03 2020 -0800

        nxstyle fixes

    commit 4afa50ba1b5db40c8b99085f5abbcc9db7fbc4e4
    Author: Adam Feuer <adam@starcat.io>
    Date:   Tue Feb 25 11:30:56 2020 -0800

        nxstyle fixes

        - note that many instances of these two errors are not being fixed:

        error: Missing blank line after comment
        error: Mixed case identifier found

        They already existed in the file before this PR, and fixing them
        seems out of character with what is there.

    commit 54f3087eb209a1b5719c9461976065137b9755f7
    Author: Adam Feuer <adam@starcat.io>
    Date:   Mon Feb 24 21:20:09 2020 -0800

        prevent GMAC txtimeout from always firing

        - and fix txbuffer leak during high-volume sends
        - improves reliability but may not have solved all issues

        Squashed commit of the following:

            commit 33c8e58c2633a6f50f18e4ad03943e8a35831995
            Author: Adam Feuer <adam@starcat.io>
            Date:   Mon Feb 24 21:17:28 2020 -0800

                removed comment line with bad copy-paste data in it

            commit c25241f29c0ae912659a2a1ad42e8a20fef8b5a0
            Author: Adam Feuer <adam@starcat.io>
            Date:   Mon Feb 24 20:57:06 2020 -0800

            prevent GMAC txtimeout from always firing

            - also prevent DMA buffer leak at fast send rates,
              for instance during large TCP sends
            - may not completely solve driver hanging
              under extreme conditions

            commit 810b860931edde137d8eb179489d23486352db8f
            Author: Adam Feuer <adam@starcat.io>
            Date:   Mon Feb 24 20:51:33 2020 -0800

                cleanup - remove debug logging, add missing struct var

            commit d7990691d2d0381294767b3afa0de94bd1e439f9
            Author: Adam Feuer <adam@starcat.io>
            Date:   Mon Feb 24 18:14:33 2020 -0800

                code cleanup

            commit 2c04aa63c6e430d92628cf779d5ee11be1c2416f
            Author: Adam Feuer <adam@starcat.io>
            Date:   Mon Feb 24 18:06:03 2020 -0800

                remove debugging info statements

            commit 1d89e6fca99184d71838d52db093a14e802e5aea
            Author: Adam Feuer <adam@starcat.io>
            Date:   Mon Feb 24 18:03:04 2020 -0800

                revert debugging comments

            commit e26a8dc5b0603d4094038cfcc633dccf54f06a59
            Author: Adam Feuer <adam@starcat.io>
            Date:   Tue Feb 18 13:48:18 2020 -0800

                better custinfo loggin

            commit 668f8743b7efb2d63a8ba0e6cac4e6bdf6dd70cb
            Author: Adam Feuer <adam@starcat.io>
            Date:   Mon Feb 17 17:13:45 2020 -0800

                fixed txtimer not being reset after transmission

            commit 169118d0ff3899854a9da00e7a007fd1bf95cb86
            Author: Adam Feuer <adam@starcat.io>
            Date:   Thu Feb 13 18:08:02 2020 -0800

                remove gmac middle-packet clauses

            commit 41022488ce3d0a7d6aacda42d3d21a1a8fe5ab47
            Author: Adam Feuer <adam@starcat.io>
            Date:   Wed Feb 12 09:12:26 2020 -0800

                added custinfo() macro

            commit 98520a78a29b85bdc7eb9d44f1169f2e036448a4
            Author: Adam Feuer <adam@starcat.io>
            Date:   Tue Feb 11 18:41:36 2020 -0800

                some refactoring, still only works with logging on

            commit 9b502f27fafbb730b4280fb3fed183834a0936bf
            Author: Adam Feuer <adam@starcat.io>
            Date:   Tue Feb 11 15:20:53 2020 -0800

                partial fix for packet size > MSS bug in GMAC

                - works ok with logging on
                - freezes at very large send sizes with logging off