drivers/wireless/ieee80211/bcm43xxx/bcmf_driver.c: Fix syslog formats
The following nxstyle errors are not trivial to fix because
they are parts of the ioctl api.

drivers/wireless/ieee80211/bcm43xxx/bcmf_driver.c:1083:34: error: Mixed case identifier found
drivers/wireless/ieee80211/bcm43xxx/bcmf_driver.c:1445:7: error: Mixed case identifier found