Fix video/video.c:1458:52: error: implicit conversion from enumeration type 'enum v4l2_buf_type' to different enumeration type 'imgsensor_stream_type_t' (aka 'enum imgsensor_stream_type_e') [-Werror,-Wenum-conversion]
ret = g_video_sensor_ops->validate_frame_setting(type, nr_fmt, sf, &si);
       ~~~~~~~~~~~~~~~~~~                         ^~~~

Signed-off-by: Xiang Xiao <xiaoxiang@xiaomi.com>
(cherry picked from commit 22f7fcbb5888531b0542903973d9d3ecb855da1a)

Change-Id: I75cf5b98d8493f099414d5115e3126ee8ec07277