Revert "sched: fix visual studio Compiler Error C2010"
This reverts commit 098b35513b09f265e90fec1893ab5f997db147be.

Reason for revert: this change make args can't be empty.

Change-Id: I8cdba975a889c2525416b3eceaebec5a431522c0